import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './voting.css';

export function Vote() {
  const [originalImageUrl, setOriginalImageUrl] = useState('placeholder.jpg');
  const [originalDescription, setOriginalDescription] = useState('Generated by API');
  const [votes, setVotes] = useState({
    player1: 0,
    player2: 0,
    player3: 0,
    player4: 0,
    player5: 0,
    player6: 0,
  });
  const [timer, setTimer] = useState(30); // 30-second timer (was 60 before)
  const [isTimerRunning, setIsTimerRunning] = useState(false); // Track if timer is active
  const navigate = useNavigate();

  useEffect(() => {
    // Check if image is already stored in sessionStorage
    const storedImage = sessionStorage.getItem('gameImage');
    if (storedImage) {
      setOriginalImageUrl(storedImage);  // Use the stored image
      setOriginalDescription('Generated by API');  // You can adjust the description based on your API
    } else {
      // Fetch a new image if not stored
      const fetchImage = async () => {
        const response = await fetch('/api/getImage');
        const data = await response.json();
        const newImageUrl = data.imageUrl;
        setOriginalImageUrl(newImageUrl);
        setOriginalDescription('Generated by API');  // You can customize this description
        sessionStorage.setItem('gameImage', newImageUrl);  // Store image URL for the round
      };

      fetchImage();
    }

    // Start the timer after a 2-second buffer
    const buffer = setTimeout(() => {
      setIsTimerRunning(true);
    }, 2000);

    return () => clearTimeout(buffer); // Cleanup on unmount
  }, []);

  useEffect(() => {
    if (isTimerRunning && timer > 0) {
      // Countdown the timer
      const countdown = setInterval(() => {
        setTimer((prev) => prev - 1);
      }, 1000);

      // Navigate to results page when timer hits zero
      if (timer === 1) {
        clearInterval(countdown);
        navigate('/results');
      }

      return () => clearInterval(countdown); // Cleanup interval on unmount
    }
  }, [isTimerRunning, timer, navigate]);

  // Function to handle voting
  const handleVote = (player) => {
    setVotes((prevVotes) => ({
      ...prevVotes,
      [player]: prevVotes[player] + 1,
    }));
  };

  return (
    <main className="container my-5">
      <div className="text-center mb-4">
        {/* Display the timer */}
        <h4>Time Left: {timer} seconds</h4>
      </div>

      <div className="row">
        <div className="col-lg-4 col-md-5">
          <div className="card p-4 shadow-lg" style={{ height: "500px" }}>
            <h3>Original Drawing</h3>
            <p>{originalDescription}</p>
            <div className="original-placeholder d-flex align-items-center justify-content-center" style={{ height: "100%", border: "2px dashed #ccc" }}>
              <img src={originalImageUrl} alt="Original drawing" style={{ maxWidth: "100%", maxHeight: "100%" }} />
            </div>
          </div>
        </div>

        <div className="col-lg-8 col-md-7 d-flex flex-wrap">
          <div className="col-12 text-center my-4">
            <h4 className="vote-heading">Vote for the Drawing that is Most Similar to the Original</h4>
          </div>
          {Object.keys(votes).map((player, index) => (
            <div key={player} className="col-lg-4 col-md-6 p-2">
              <button
                className="card p-2 shadow-sm w-100"
                onClick={() => handleVote(player)}
                style={{ cursor: 'pointer' }}
              >
                <h5 className="text-center">Player {index + 1}</h5>
                <p>[Player {index + 1} Drawing Placeholder]</p>
                <p className="text-center">Votes: {votes[player]}</p>
              </button>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
