import React from 'react';
import './voting.css';

export function Vote() {
  return (
    <main className="container my-5">
        <div className="row">
            <div className="col-lg-4 col-md-5">
                <div className="card p-4 shadow-lg" style={{ height: "500px" }}>
                    <h3>Original Drawing</h3>
                    <p>(Generated by API)</p>
                    <div className="original-placeholder d-flex align-items-center justify-content-center" style={{ height: "100%", border: "2px dashed #ccc" }}>
                        <p>[Original Drawing Placeholder]</p>
                    </div>
                </div>
            </div>

            <div className="col-lg-8 col-md-7 d-flex flex-wrap">
                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 1</h5>
                        <p>[Player 1 Drawing Placeholder]</p>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 2</h5>
                        <p>[Player 2 Drawing Placeholder]</p>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 3</h5>
                        <p>[Player 3 Drawing Placeholder]</p>
                    </div>
                </div>

                <div className="col-12 text-center my-4">
                    <h4>Vote for the Drawing that is Most Similar to the Original</h4>
                </div>

                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 4</h5>
                        <p>[Player 4 Drawing Placeholder]</p>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 5</h5>
                        <p>[Player 5 Drawing Placeholder]</p>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6 p-2">
                    <div className="card p-2 shadow-sm">
                        <h5 className="text-center">Player 6</h5>
                        <p>[Player 6 Drawing Placeholder]</p>
                    </div>
                </div>
            </div>
        </div>
        <div className="text-center mt-5">
            <a href="/lobby" className="btn btn-secondary">Back to Lobby</a>
        </div>
    </main>
  );
}
