import React, { useState, useEffect } from 'react'; 
import { useNavigate } from 'react-router-dom';
import './voting.css';

export function Vote({ currentUser }) {
  const [originalImageUrl, setOriginalImageUrl] = useState('placeholder.jpg');
  const [originalDescription, setOriginalDescription] = useState('Generated by API');
  const [votes, setVotes] = useState({
    player1: 0,
    player2: 0,
    player3: 0,
    player4: 0,
    player5: 0,
    player6: 0,
  });
  const [timer, setTimer] = useState(30); // 30-second timer
  const [isTimerRunning, setIsTimerRunning] = useState(false); // Track if timer is active
  const navigate = useNavigate();

  // Fetch image (same as before)
  useEffect(() => {
    const storedImage = sessionStorage.getItem('gameImage');
    if (storedImage) {
      setOriginalImageUrl(storedImage);  
      setOriginalDescription('Generated by API'); 
    } else {
      const fetchImage = async () => {
        const response = await fetch('/api/getImage');
        const data = await response.json();
        const newImageUrl = data.imageUrl;
        setOriginalImageUrl(newImageUrl);
        setOriginalDescription('Generated by API');
        sessionStorage.setItem('gameImage', newImageUrl);
      };
      fetchImage();
    }

    const buffer = setTimeout(() => {
      setIsTimerRunning(true);
    }, 2000);

    return () => clearTimeout(buffer); // Cleanup on unmount
  }, []);

  // Timer functionality
  useEffect(() => {
    if (isTimerRunning && timer > 0) {
      const countdown = setInterval(() => {
        setTimer((prev) => prev - 1);
      }, 1000);

      if (timer === 1) {
        clearInterval(countdown);
        navigate('/results'); // Go to results when time is up
      }

      return () => clearInterval(countdown); // Cleanup interval on unmount
    }
  }, [isTimerRunning, timer, navigate]);

  // Function to handle voting
  const handleVote = async (player) => {
    // Register vote for the player
    setVotes((prevVotes) => ({
      ...prevVotes,
      [player]: prevVotes[player] + 1,
    }));

    // Check if the current user wins the round
    if (player === currentUser) {
      try {
        // Send the vote result to the backend to update the score of the current user
        const response = await fetch('/api/updateScore', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            username: currentUser,
            points: 1, // Add 1 point for the current user if they win
          }),
        });

        if (response.ok) {
          console.log('Score updated');
        } else {
          console.error('Error updating score');
        }
      } catch (error) {
        console.error('Error updating score:', error);
      }
    }
  };

  return (
    <main className="container my-5">
      <div className="text-center mb-4">
        <h4>Time Left: {timer} seconds</h4>
      </div>

      <div className="row">
        <div className="col-lg-4 col-md-5">
          <div className="card p-4 shadow-lg" style={{ height: "500px" }}>
            <h3>Original Drawing</h3>
            <p>{originalDescription}</p>
            <div className="original-placeholder d-flex align-items-center justify-content-center" style={{ height: "100%", border: "2px dashed #ccc" }}>
              <img src={originalImageUrl} alt="Original drawing" style={{ maxWidth: "100%", maxHeight: "100%" }} />
            </div>
          </div>
        </div>

        <div className="col-lg-8 col-md-7 d-flex flex-wrap">
          <div className="col-12 text-center my-4">
            <h4 className="vote-heading">Vote for the Drawing that is Most Similar to the Original</h4>
          </div>

          {/* Display each player's votes */}
          {Object.keys(votes).map((player, index) => (
            <div key={player} className="col-lg-4 col-md-6 p-2">
              <button
                className="card p-2 shadow-sm w-100"
                onClick={() => handleVote(player)}
                style={{ cursor: 'pointer' }}
              >
                <h5 className="text-center">Player {index + 1}</h5>
                <p>[Player {index + 1} Drawing Placeholder]</p>
                <p className="text-center">Votes: {votes[player]}</p>
              </button>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
